filebeat.registry.path: /usr/share/filebeat/data/registry

filebeat.config.inputs:
  path: ${path.config}/config/*.yml
  reload.enabled: true

processors:
  - add_host_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

logging.to_files: false

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]
