filebeat.registry.path: /usr/share/filebeat/data/registry

filebeat.config.inputs:
  path: ${path.config}/config/*.yml
  reload.enabled: true

processors:
  - add_host_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "structure"

setup:
  ilm:
    enabled: true
    rollover_alias: "structure"
    pattern: "{now/M{yyyy.MM}}-00"
  template:
    pattern: "structure"
    name: "structure"
    settings.index:
      number_of_shards: 1
      number_of_replicas: 0

logging.to_files: false

xpack.monitoring:
  enabled: true
  elasticsearch: ~
