metricbeat.config.modules:
  path: ${path.config}/config/*.yml
  reload.period: 10s

processors:
  - add_docker_metadata: ~
  - add_host_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup:
  template.settings.index:
    number_of_shards: 1
    number_of_replicas: 0
  kibana.host: "kibana:5601"
  dashboards.enabled: true

logging.to_files: false

xpack.monitoring:
  enabled: true
  elasticsearch: ~
